/**
 * Centralized error codes for the entire application
 * This is the single source of truth for all error codes
 */

export const AUTH_ERRORS = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
} as const;

export const VALIDATION_ERRORS = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_URL: "INVALID_URL",
  INVALID_DATE: "INVALID_DATE",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
} as const;

export const NOT_FOUND_ERRORS = {
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  POST_NOT_FOUND: "POST_NOT_FOUND",
  BLOG_NOT_FOUND: "BLOG_NOT_FOUND",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
  PRACTITIONER_NOT_FOUND: "PRACTITIONER_NOT_FOUND",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  WEBINAR_NOT_FOUND: "WEBINAR_NOT_FOUND",
  YOGA_NOT_FOUND: "YOGA_NOT_FOUND",
} as const;

export const RATE_LIMIT_ERRORS = {
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  TOO_MANY_LOGIN_ATTEMPTS: "TOO_MANY_LOGIN_ATTEMPTS",
  TOO_MANY_PASSWORD_RESET_ATTEMPTS: "TOO_MANY_PASSWORD_RESET_ATTEMPTS",
} as const;

export const DATABASE_ERRORS = {
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  QUERY_EXECUTION_ERROR: "QUERY_EXECUTION_ERROR",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
} as const;

export const CRUD_ERRORS = {
  CREATE_FAILED: "CREATE_FAILED",
  READ_FAILED: "READ_FAILED",
  UPDATE_FAILED: "UPDATE_FAILED",
  DELETE_FAILED: "DELETE_FAILED",
  FETCH_FAILED: "FETCH_FAILED",
} as const;

export const DASHBOARD_ERRORS = {
  DASHBOARD_DATA_FETCH_ERROR: "DASHBOARD_DATA_FETCH_ERROR",
  DASHBOARD_LOAD_FAILED: "DASHBOARD_LOAD_FAILED",
  DASHBOARD_STATS_FETCH_ERROR: "DASHBOARD_STATS_FETCH_ERROR",
  DASHBOARD_CHART_DATA_ERROR: "DASHBOARD_CHART_DATA_ERROR",
} as const;

export const USER_ERRORS = {
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",
  USER_FETCH_FAILED: "USER_FETCH_FAILED",
  USER_PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED",
  USER_PASSWORD_CHANGE_FAILED: "USER_PASSWORD_CHANGE_FAILED",
} as const;

export const POST_ERRORS = {
  POST_CREATION_FAILED: "POST_CREATION_FAILED",
  POST_UPDATE_FAILED: "POST_UPDATE_FAILED",
  POST_DELETE_FAILED: "POST_DELETE_FAILED",
  POST_FETCH_FAILED: "POST_FETCH_FAILED",
  POST_PUBLISH_FAILED: "POST_PUBLISH_FAILED",
} as const;

export const BLOG_ERRORS = {
  BLOG_CREATION_FAILED: "BLOG_CREATION_FAILED",
  BLOG_UPDATE_FAILED: "BLOG_UPDATE_FAILED",
  BLOG_DELETE_FAILED: "BLOG_DELETE_FAILED",
  BLOG_FETCH_FAILED: "BLOG_FETCH_FAILED",
} as const;

export const CATEGORY_ERRORS = {
  CATEGORY_CREATION_FAILED: "CATEGORY_CREATION_FAILED",
  CATEGORY_UPDATE_FAILED: "CATEGORY_UPDATE_FAILED",
  CATEGORY_DELETE_FAILED: "CATEGORY_DELETE_FAILED",
  CATEGORY_FETCH_FAILED: "CATEGORY_FETCH_FAILED",
} as const;

export const FILE_ERRORS = {
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_PROCESSING_ERROR: "FILE_PROCESSING_ERROR",
} as const;

export const EXTERNAL_SERVICE_ERRORS = {
  UPLOADCARE_ERROR: "UPLOADCARE_ERROR",
  EMAIL_SERVICE_ERROR: "EMAIL_SERVICE_ERROR",
  SMS_SERVICE_ERROR: "SMS_SERVICE_ERROR",
  HALAXY_API_ERROR: "HALAXY_API_ERROR",
  PAYMENT_SERVICE_ERROR: "PAYMENT_SERVICE_ERROR",
} as const;

export const SERVER_ERRORS = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  TIMEOUT: "TIMEOUT",
} as const;

export const ERROR_CODES = {
  ...AUTH_ERRORS,
  ...VALIDATION_ERRORS,
  ...NOT_FOUND_ERRORS,
  ...RATE_LIMIT_ERRORS,
  ...DATABASE_ERRORS,
  ...CRUD_ERRORS,
  ...DASHBOARD_ERRORS,
  ...USER_ERRORS,
  ...POST_ERRORS,
  ...BLOG_ERRORS,
  ...CATEGORY_ERRORS,
  ...FILE_ERRORS,
  ...EXTERNAL_SERVICE_ERRORS,
  ...SERVER_ERRORS,
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];